name: ci_demo

on:
  push:
    branches:
      - main  # Trigger on push to 'main' branch
  pull_request:
    branches:
      - main  # Trigger on new or updated pull requests targeting 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step to clone the repo
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step to set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step to install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step to run pytest
      - name: Run Tests
        run: pytest .
