name: ci_demo

on:
  push:
    branches:
      - github_actions  # This specific branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step to clone the repo
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step to set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # You can specify a different version if needed

      # Step to install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step to run pytest
      - name: Run Tests
        run: pytest .
